-- Sql script to create table
CREATE TABLE USER
(
    USERNAME VARCHAR(20),
    PASSWORD VARCHAR(255) NOT NULL,
    FIRSTNAME VARCHAR(20) NOT NULL,
    LASTNAME VARCHAR(20) NOT NULL,
    EMAIL VARCHAR(40) NOT NULL,
    PRIMARY KEY(USERNAME)
);
